### ISSUE TITLE
mysql connection closed without retry

### ISSUE THREAD

**Issue by liuhuiping2013** [braedon/prometheus-mysql-exporter#14]
i have run this app for long time, everything is well before mysql connection lost:

> Traceback (most recent call last):  
File "/usr/src/app/prometheus_mysql_exporter/__init__.py", line 44, in run_query  
  mysql_client.select_db(db_name)  
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')  

this error will never recover, unless restart the app.

Can you provide reconnection options?
thanks.

**Comment by braedon** [comment]
Hi @liuhuiping2013, thanks for reporting this. I'll work on getting it to automatically re-connect.

**Comment by braedon** [comment]
Fix released in [0.4.0](https://github.com/braedon/prometheus-mysql-exporter/releases/tag/0.4.0).
