### ISSUE TITLE
Feature: allow queries at defined times (a.k.a. cron-like)

### ISSUE THREAD

**Issue by svenXY** [braedon/prometheus-mysql-exporter#17]
Hi,

it would be great to be able to run some queries at certain times, like at 00:00 or similar. We have queries that count certain things and want to have precise numbers (x per day and similar)

scheduler.enterabs(time, priority, action, argument=(), kwargs={}) allows to set a time, so it would be necessary to change schedule_event to allow to either set a query_every or query_at.

**Comment by svenXY** [comment]
Hi, I've made PR #18 to implement this, maybe you'd like to take a look at it

Cheers,
Sven

**Comment by braedon** [comment]
Hi @svenXY, sorry for the long delay.

I wanted to keep the MySQL reconnection change separate, and change the cron implementation a bit, so I made a new branch from your main commit. There's some explanation of the changes in [the commit message](https://github.com/braedon/prometheus-mysql-exporter/pull/20/commits/c372b139cbc95718c1ff15109454278970585507).

Please review https://github.com/braedon/prometheus-mysql-exporter/pull/20 and let me know if it'll still work for you. If so, I'll get it merged in ASAP.

**Comment by braedon** [comment]
Released in [0.5.0](https://github.com/braedon/prometheus-mysql-exporter/releases/tag/0.5.0)
