### ISSUE TITLE
How to user your code?

### ISSUE THREAD

**Issue by jinhang** [Braedon/prometheus-mysql-exporter#2]
hi,could you give me an example?

**Comment by Braedon** [comment]
Hi @jinhang,

The [README.md](https://github.com/Braedon/prometheus-mysql-exporter/blob/master/README.md) shows how to install and run the app, and [exporter.cfg](https://github.com/Braedon/prometheus-mysql-exporter/blob/master/exporter.cfg) has a simple example query.

If anything isn't clear, or you are having issues with any specific part, let me know and I'll be happy to help.

Braedon
