### ISSUE TITLE
Using the symbol %.

### ISSUE THREAD

**Issue by YevgeniyBushuyev** [Braedon/prometheus-mysql-exporter#21]
Hello. I'm sorry, I don't know if I'm asking the question in the right place. I have a problem when using your prometheus-mysql-exporter. Select does not work when I use the '%' sign in the selection conditions. Example: select count(*) from db1.table1 t where t.field1 LIKE '%[TEST_1#TEST_2]%', container does not start.

**Comment by braedon** [comment]
Hi @YevgeniyBushuyev, that's because `%` has a special meaning in the config file format - it's used for [value interpolation](https://docs.python.org/3/library/configparser.html#interpolation-of-values). You'll need to escape any `%` with another `%`, e.g.:

```
QueryStatement = select count(*) from db1.table1 t where t.field1 LIKE '%%[TEST_1#TEST_2]%%';
```

**Comment by YevgeniyBushuyev** [comment]
Hi @braedon tnx!
